// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/meta_graph.proto

package org.tensorflow.framework;

public interface CollectionDefOrBuilder extends
        // @@protoc_insertion_point(interface_extends:tensorflow.CollectionDef)
        com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .tensorflow.CollectionDef.NodeList node_list = 1;</code>
   */
  CollectionDef.NodeList getNodeList();
  /**
   * <code>optional .tensorflow.CollectionDef.NodeList node_list = 1;</code>
   */
  CollectionDef.NodeListOrBuilder getNodeListOrBuilder();

  /**
   * <code>optional .tensorflow.CollectionDef.BytesList bytes_list = 2;</code>
   */
  CollectionDef.BytesList getBytesList();
  /**
   * <code>optional .tensorflow.CollectionDef.BytesList bytes_list = 2;</code>
   */
  CollectionDef.BytesListOrBuilder getBytesListOrBuilder();

  /**
   * <code>optional .tensorflow.CollectionDef.Int64List int64_list = 3;</code>
   */
  CollectionDef.Int64List getInt64List();
  /**
   * <code>optional .tensorflow.CollectionDef.Int64List int64_list = 3;</code>
   */
  CollectionDef.Int64ListOrBuilder getInt64ListOrBuilder();

  /**
   * <code>optional .tensorflow.CollectionDef.FloatList float_list = 4;</code>
   */
  CollectionDef.FloatList getFloatList();
  /**
   * <code>optional .tensorflow.CollectionDef.FloatList float_list = 4;</code>
   */
  CollectionDef.FloatListOrBuilder getFloatListOrBuilder();

  /**
   * <code>optional .tensorflow.CollectionDef.AnyList any_list = 5;</code>
   */
  CollectionDef.AnyList getAnyList();
  /**
   * <code>optional .tensorflow.CollectionDef.AnyList any_list = 5;</code>
   */
  CollectionDef.AnyListOrBuilder getAnyListOrBuilder();

  public CollectionDef.KindCase getKindCase();
}
