// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/device_attributes.proto

package org.tensorflow.framework;

/**
 * Protobuf type {@code tensorflow.DeviceLocality}
 */
public  final class DeviceLocality extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tensorflow.DeviceLocality)
    DeviceLocalityOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DeviceLocality.newBuilder() to construct.
  private DeviceLocality(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DeviceLocality() {
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DeviceLocality(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            busId_ = input.readInt32();
            break;
          }
          case 16: {

            numaNode_ = input.readInt32();
            break;
          }
          case 26: {
            LocalLinks.Builder subBuilder = null;
            if (links_ != null) {
              subBuilder = links_.toBuilder();
            }
            links_ = input.readMessage(LocalLinks.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(links_);
              links_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return DeviceAttributesProtos.internal_static_tensorflow_DeviceLocality_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return DeviceAttributesProtos.internal_static_tensorflow_DeviceLocality_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            DeviceLocality.class, Builder.class);
  }

  public static final int BUS_ID_FIELD_NUMBER = 1;
  private int busId_;
  /**
   * <pre>
   * Optional bus locality of device.  Default value of 0 means
   * no specific locality.  Specific localities are indexed from 1.
   * </pre>
   *
   * <code>int32 bus_id = 1;</code>
   */
  public int getBusId() {
    return busId_;
  }

  public static final int NUMA_NODE_FIELD_NUMBER = 2;
  private int numaNode_;
  /**
   * <pre>
   * Optional NUMA locality of device.
   * </pre>
   *
   * <code>int32 numa_node = 2;</code>
   */
  public int getNumaNode() {
    return numaNode_;
  }

  public static final int LINKS_FIELD_NUMBER = 3;
  private LocalLinks links_;
  /**
   * <pre>
   * Optional local interconnect links to other devices.
   * </pre>
   *
   * <code>.tensorflow.LocalLinks links = 3;</code>
   */
  public boolean hasLinks() {
    return links_ != null;
  }
  /**
   * <pre>
   * Optional local interconnect links to other devices.
   * </pre>
   *
   * <code>.tensorflow.LocalLinks links = 3;</code>
   */
  public LocalLinks getLinks() {
    return links_ == null ? LocalLinks.getDefaultInstance() : links_;
  }
  /**
   * <pre>
   * Optional local interconnect links to other devices.
   * </pre>
   *
   * <code>.tensorflow.LocalLinks links = 3;</code>
   */
  public LocalLinksOrBuilder getLinksOrBuilder() {
    return getLinks();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (busId_ != 0) {
      output.writeInt32(1, busId_);
    }
    if (numaNode_ != 0) {
      output.writeInt32(2, numaNode_);
    }
    if (links_ != null) {
      output.writeMessage(3, getLinks());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (busId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, busId_);
    }
    if (numaNode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, numaNode_);
    }
    if (links_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getLinks());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof DeviceLocality)) {
      return super.equals(obj);
    }
    DeviceLocality other = (DeviceLocality) obj;

    if (getBusId()
        != other.getBusId()) return false;
    if (getNumaNode()
        != other.getNumaNode()) return false;
    if (hasLinks() != other.hasLinks()) return false;
    if (hasLinks()) {
      if (!getLinks()
          .equals(other.getLinks())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BUS_ID_FIELD_NUMBER;
    hash = (53 * hash) + getBusId();
    hash = (37 * hash) + NUMA_NODE_FIELD_NUMBER;
    hash = (53 * hash) + getNumaNode();
    if (hasLinks()) {
      hash = (37 * hash) + LINKS_FIELD_NUMBER;
      hash = (53 * hash) + getLinks().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static DeviceLocality parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DeviceLocality parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DeviceLocality parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DeviceLocality parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DeviceLocality parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DeviceLocality parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DeviceLocality parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DeviceLocality parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static DeviceLocality parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static DeviceLocality parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static DeviceLocality parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DeviceLocality parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(DeviceLocality prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tensorflow.DeviceLocality}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tensorflow.DeviceLocality)
      DeviceLocalityOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DeviceAttributesProtos.internal_static_tensorflow_DeviceLocality_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DeviceAttributesProtos.internal_static_tensorflow_DeviceLocality_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DeviceLocality.class, Builder.class);
    }

    // Construct using org.tensorflow.framework.DeviceLocality.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      busId_ = 0;

      numaNode_ = 0;

      if (linksBuilder_ == null) {
        links_ = null;
      } else {
        links_ = null;
        linksBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return DeviceAttributesProtos.internal_static_tensorflow_DeviceLocality_descriptor;
    }

    @Override
    public DeviceLocality getDefaultInstanceForType() {
      return DeviceLocality.getDefaultInstance();
    }

    @Override
    public DeviceLocality build() {
      DeviceLocality result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public DeviceLocality buildPartial() {
      DeviceLocality result = new DeviceLocality(this);
      result.busId_ = busId_;
      result.numaNode_ = numaNode_;
      if (linksBuilder_ == null) {
        result.links_ = links_;
      } else {
        result.links_ = linksBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof DeviceLocality) {
        return mergeFrom((DeviceLocality)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(DeviceLocality other) {
      if (other == DeviceLocality.getDefaultInstance()) return this;
      if (other.getBusId() != 0) {
        setBusId(other.getBusId());
      }
      if (other.getNumaNode() != 0) {
        setNumaNode(other.getNumaNode());
      }
      if (other.hasLinks()) {
        mergeLinks(other.getLinks());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      DeviceLocality parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (DeviceLocality) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int busId_ ;
    /**
     * <pre>
     * Optional bus locality of device.  Default value of 0 means
     * no specific locality.  Specific localities are indexed from 1.
     * </pre>
     *
     * <code>int32 bus_id = 1;</code>
     */
    public int getBusId() {
      return busId_;
    }
    /**
     * <pre>
     * Optional bus locality of device.  Default value of 0 means
     * no specific locality.  Specific localities are indexed from 1.
     * </pre>
     *
     * <code>int32 bus_id = 1;</code>
     */
    public Builder setBusId(int value) {

      busId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional bus locality of device.  Default value of 0 means
     * no specific locality.  Specific localities are indexed from 1.
     * </pre>
     *
     * <code>int32 bus_id = 1;</code>
     */
    public Builder clearBusId() {

      busId_ = 0;
      onChanged();
      return this;
    }

    private int numaNode_ ;
    /**
     * <pre>
     * Optional NUMA locality of device.
     * </pre>
     *
     * <code>int32 numa_node = 2;</code>
     */
    public int getNumaNode() {
      return numaNode_;
    }
    /**
     * <pre>
     * Optional NUMA locality of device.
     * </pre>
     *
     * <code>int32 numa_node = 2;</code>
     */
    public Builder setNumaNode(int value) {

      numaNode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional NUMA locality of device.
     * </pre>
     *
     * <code>int32 numa_node = 2;</code>
     */
    public Builder clearNumaNode() {

      numaNode_ = 0;
      onChanged();
      return this;
    }

    private LocalLinks links_;
    private com.google.protobuf.SingleFieldBuilderV3<
        LocalLinks, LocalLinks.Builder, LocalLinksOrBuilder> linksBuilder_;
    /**
     * <pre>
     * Optional local interconnect links to other devices.
     * </pre>
     *
     * <code>.tensorflow.LocalLinks links = 3;</code>
     */
    public boolean hasLinks() {
      return linksBuilder_ != null || links_ != null;
    }
    /**
     * <pre>
     * Optional local interconnect links to other devices.
     * </pre>
     *
     * <code>.tensorflow.LocalLinks links = 3;</code>
     */
    public LocalLinks getLinks() {
      if (linksBuilder_ == null) {
        return links_ == null ? LocalLinks.getDefaultInstance() : links_;
      } else {
        return linksBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Optional local interconnect links to other devices.
     * </pre>
     *
     * <code>.tensorflow.LocalLinks links = 3;</code>
     */
    public Builder setLinks(LocalLinks value) {
      if (linksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        links_ = value;
        onChanged();
      } else {
        linksBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Optional local interconnect links to other devices.
     * </pre>
     *
     * <code>.tensorflow.LocalLinks links = 3;</code>
     */
    public Builder setLinks(
        LocalLinks.Builder builderForValue) {
      if (linksBuilder_ == null) {
        links_ = builderForValue.build();
        onChanged();
      } else {
        linksBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Optional local interconnect links to other devices.
     * </pre>
     *
     * <code>.tensorflow.LocalLinks links = 3;</code>
     */
    public Builder mergeLinks(LocalLinks value) {
      if (linksBuilder_ == null) {
        if (links_ != null) {
          links_ =
            LocalLinks.newBuilder(links_).mergeFrom(value).buildPartial();
        } else {
          links_ = value;
        }
        onChanged();
      } else {
        linksBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Optional local interconnect links to other devices.
     * </pre>
     *
     * <code>.tensorflow.LocalLinks links = 3;</code>
     */
    public Builder clearLinks() {
      if (linksBuilder_ == null) {
        links_ = null;
        onChanged();
      } else {
        links_ = null;
        linksBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Optional local interconnect links to other devices.
     * </pre>
     *
     * <code>.tensorflow.LocalLinks links = 3;</code>
     */
    public LocalLinks.Builder getLinksBuilder() {

      onChanged();
      return getLinksFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Optional local interconnect links to other devices.
     * </pre>
     *
     * <code>.tensorflow.LocalLinks links = 3;</code>
     */
    public LocalLinksOrBuilder getLinksOrBuilder() {
      if (linksBuilder_ != null) {
        return linksBuilder_.getMessageOrBuilder();
      } else {
        return links_ == null ?
            LocalLinks.getDefaultInstance() : links_;
      }
    }
    /**
     * <pre>
     * Optional local interconnect links to other devices.
     * </pre>
     *
     * <code>.tensorflow.LocalLinks links = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        LocalLinks, LocalLinks.Builder, LocalLinksOrBuilder>
        getLinksFieldBuilder() {
      if (linksBuilder_ == null) {
        linksBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            LocalLinks, LocalLinks.Builder, LocalLinksOrBuilder>(
                getLinks(),
                getParentForChildren(),
                isClean());
        links_ = null;
      }
      return linksBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tensorflow.DeviceLocality)
  }

  // @@protoc_insertion_point(class_scope:tensorflow.DeviceLocality)
  private static final DeviceLocality DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new DeviceLocality();
  }

  public static DeviceLocality getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DeviceLocality>
      PARSER = new com.google.protobuf.AbstractParser<DeviceLocality>() {
    @Override
    public DeviceLocality parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DeviceLocality(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DeviceLocality> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<DeviceLocality> getParserForType() {
    return PARSER;
  }

  @Override
  public DeviceLocality getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

