// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/meta_graph.proto

package org.tensorflow.framework;

import org.tensorflow.util.SaverDef;
import org.tensorflow.util.SaverDefOrBuilder;

public interface MetaGraphDefOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.MetaGraphDef)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tensorflow.MetaGraphDef.MetaInfoDef meta_info_def = 1;</code>
   */
  boolean hasMetaInfoDef();
  /**
   * <code>.tensorflow.MetaGraphDef.MetaInfoDef meta_info_def = 1;</code>
   */
  MetaGraphDef.MetaInfoDef getMetaInfoDef();
  /**
   * <code>.tensorflow.MetaGraphDef.MetaInfoDef meta_info_def = 1;</code>
   */
  MetaGraphDef.MetaInfoDefOrBuilder getMetaInfoDefOrBuilder();

  /**
   * <pre>
   * GraphDef.
   * </pre>
   *
   * <code>.tensorflow.GraphDef graph_def = 2;</code>
   */
  boolean hasGraphDef();
  /**
   * <pre>
   * GraphDef.
   * </pre>
   *
   * <code>.tensorflow.GraphDef graph_def = 2;</code>
   */
  GraphDef getGraphDef();
  /**
   * <pre>
   * GraphDef.
   * </pre>
   *
   * <code>.tensorflow.GraphDef graph_def = 2;</code>
   */
  GraphDefOrBuilder getGraphDefOrBuilder();

  /**
   * <pre>
   * SaverDef.
   * </pre>
   *
   * <code>.tensorflow.SaverDef saver_def = 3;</code>
   */
  boolean hasSaverDef();
  /**
   * <pre>
   * SaverDef.
   * </pre>
   *
   * <code>.tensorflow.SaverDef saver_def = 3;</code>
   */
  SaverDef getSaverDef();
  /**
   * <pre>
   * SaverDef.
   * </pre>
   *
   * <code>.tensorflow.SaverDef saver_def = 3;</code>
   */
  SaverDefOrBuilder getSaverDefOrBuilder();

  /**
   * <pre>
   * collection_def: Map from collection name to collections.
   * See CollectionDef section for details.
   * </pre>
   *
   * <code>map&lt;string, .tensorflow.CollectionDef&gt; collection_def = 4;</code>
   */
  int getCollectionDefCount();
  /**
   * <pre>
   * collection_def: Map from collection name to collections.
   * See CollectionDef section for details.
   * </pre>
   *
   * <code>map&lt;string, .tensorflow.CollectionDef&gt; collection_def = 4;</code>
   */
  boolean containsCollectionDef(
          String key);
  /**
   * Use {@link #getCollectionDefMap()} instead.
   */
  @Deprecated
  java.util.Map<String, CollectionDef>
  getCollectionDef();
  /**
   * <pre>
   * collection_def: Map from collection name to collections.
   * See CollectionDef section for details.
   * </pre>
   *
   * <code>map&lt;string, .tensorflow.CollectionDef&gt; collection_def = 4;</code>
   */
  java.util.Map<String, CollectionDef>
  getCollectionDefMap();
  /**
   * <pre>
   * collection_def: Map from collection name to collections.
   * See CollectionDef section for details.
   * </pre>
   *
   * <code>map&lt;string, .tensorflow.CollectionDef&gt; collection_def = 4;</code>
   */

  CollectionDef getCollectionDefOrDefault(
          String key,
          CollectionDef defaultValue);
  /**
   * <pre>
   * collection_def: Map from collection name to collections.
   * See CollectionDef section for details.
   * </pre>
   *
   * <code>map&lt;string, .tensorflow.CollectionDef&gt; collection_def = 4;</code>
   */

  CollectionDef getCollectionDefOrThrow(
          String key);

  /**
   * <pre>
   * signature_def: Map from user supplied key for a signature to a single
   * SignatureDef.
   * </pre>
   *
   * <code>map&lt;string, .tensorflow.SignatureDef&gt; signature_def = 5;</code>
   */
  int getSignatureDefCount();
  /**
   * <pre>
   * signature_def: Map from user supplied key for a signature to a single
   * SignatureDef.
   * </pre>
   *
   * <code>map&lt;string, .tensorflow.SignatureDef&gt; signature_def = 5;</code>
   */
  boolean containsSignatureDef(
          String key);
  /**
   * Use {@link #getSignatureDefMap()} instead.
   */
  @Deprecated
  java.util.Map<String, SignatureDef>
  getSignatureDef();
  /**
   * <pre>
   * signature_def: Map from user supplied key for a signature to a single
   * SignatureDef.
   * </pre>
   *
   * <code>map&lt;string, .tensorflow.SignatureDef&gt; signature_def = 5;</code>
   */
  java.util.Map<String, SignatureDef>
  getSignatureDefMap();
  /**
   * <pre>
   * signature_def: Map from user supplied key for a signature to a single
   * SignatureDef.
   * </pre>
   *
   * <code>map&lt;string, .tensorflow.SignatureDef&gt; signature_def = 5;</code>
   */

  SignatureDef getSignatureDefOrDefault(
          String key,
          SignatureDef defaultValue);
  /**
   * <pre>
   * signature_def: Map from user supplied key for a signature to a single
   * SignatureDef.
   * </pre>
   *
   * <code>map&lt;string, .tensorflow.SignatureDef&gt; signature_def = 5;</code>
   */

  SignatureDef getSignatureDefOrThrow(
          String key);

  /**
   * <pre>
   * Asset file def to be used with the defined graph.
   * </pre>
   *
   * <code>repeated .tensorflow.AssetFileDef asset_file_def = 6;</code>
   */
  java.util.List<AssetFileDef>
      getAssetFileDefList();
  /**
   * <pre>
   * Asset file def to be used with the defined graph.
   * </pre>
   *
   * <code>repeated .tensorflow.AssetFileDef asset_file_def = 6;</code>
   */
  AssetFileDef getAssetFileDef(int index);
  /**
   * <pre>
   * Asset file def to be used with the defined graph.
   * </pre>
   *
   * <code>repeated .tensorflow.AssetFileDef asset_file_def = 6;</code>
   */
  int getAssetFileDefCount();
  /**
   * <pre>
   * Asset file def to be used with the defined graph.
   * </pre>
   *
   * <code>repeated .tensorflow.AssetFileDef asset_file_def = 6;</code>
   */
  java.util.List<? extends AssetFileDefOrBuilder>
      getAssetFileDefOrBuilderList();
  /**
   * <pre>
   * Asset file def to be used with the defined graph.
   * </pre>
   *
   * <code>repeated .tensorflow.AssetFileDef asset_file_def = 6;</code>
   */
  AssetFileDefOrBuilder getAssetFileDefOrBuilder(
          int index);
}
