// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/example/example_parser_configuration.proto

package org.tensorflow.example;

public interface ExampleParserConfigurationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.ExampleParserConfiguration)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .tensorflow.FeatureConfiguration&gt; feature_map = 1;</code>
   */
  int getFeatureMapCount();
  /**
   * <code>map&lt;string, .tensorflow.FeatureConfiguration&gt; feature_map = 1;</code>
   */
  boolean containsFeatureMap(
          String key);
  /**
   * Use {@link #getFeatureMapMap()} instead.
   */
  @Deprecated
  java.util.Map<String, FeatureConfiguration>
  getFeatureMap();
  /**
   * <code>map&lt;string, .tensorflow.FeatureConfiguration&gt; feature_map = 1;</code>
   */
  java.util.Map<String, FeatureConfiguration>
  getFeatureMapMap();
  /**
   * <code>map&lt;string, .tensorflow.FeatureConfiguration&gt; feature_map = 1;</code>
   */

  FeatureConfiguration getFeatureMapOrDefault(
          String key,
          FeatureConfiguration defaultValue);
  /**
   * <code>map&lt;string, .tensorflow.FeatureConfiguration&gt; feature_map = 1;</code>
   */

  FeatureConfiguration getFeatureMapOrThrow(
          String key);
}
