// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/example/example_parser_configuration.proto

package org.tensorflow.example;

/**
 * Protobuf type {@code tensorflow.ExampleParserConfiguration}
 */
public  final class ExampleParserConfiguration extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tensorflow.ExampleParserConfiguration)
    ExampleParserConfigurationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExampleParserConfiguration.newBuilder() to construct.
  private ExampleParserConfiguration(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExampleParserConfiguration() {
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ExampleParserConfiguration(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              featureMap_ = com.google.protobuf.MapField.newMapField(
                  FeatureMapDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<String, FeatureConfiguration>
            featureMap__ = input.readMessage(
                FeatureMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            featureMap_.getMutableMap().put(
                featureMap__.getKey(), featureMap__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ExampleParserConfigurationProtos.internal_static_tensorflow_ExampleParserConfiguration_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetFeatureMap();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ExampleParserConfigurationProtos.internal_static_tensorflow_ExampleParserConfiguration_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ExampleParserConfiguration.class, Builder.class);
  }

  public static final int FEATURE_MAP_FIELD_NUMBER = 1;
  private static final class FeatureMapDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        String, FeatureConfiguration> defaultEntry =
            com.google.protobuf.MapEntry
            .<String, FeatureConfiguration>newDefaultInstance(
                ExampleParserConfigurationProtos.internal_static_tensorflow_ExampleParserConfiguration_FeatureMapEntry_descriptor,
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                FeatureConfiguration.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      String, FeatureConfiguration> featureMap_;
  private com.google.protobuf.MapField<String, FeatureConfiguration>
  internalGetFeatureMap() {
    if (featureMap_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          FeatureMapDefaultEntryHolder.defaultEntry);
    }
    return featureMap_;
  }

  public int getFeatureMapCount() {
    return internalGetFeatureMap().getMap().size();
  }
  /**
   * <code>map&lt;string, .tensorflow.FeatureConfiguration&gt; feature_map = 1;</code>
   */

  public boolean containsFeatureMap(
      String key) {
    if (key == null) { throw new NullPointerException(); }
    return internalGetFeatureMap().getMap().containsKey(key);
  }
  /**
   * Use {@link #getFeatureMapMap()} instead.
   */
  @Deprecated
  public java.util.Map<String, FeatureConfiguration> getFeatureMap() {
    return getFeatureMapMap();
  }
  /**
   * <code>map&lt;string, .tensorflow.FeatureConfiguration&gt; feature_map = 1;</code>
   */

  public java.util.Map<String, FeatureConfiguration> getFeatureMapMap() {
    return internalGetFeatureMap().getMap();
  }
  /**
   * <code>map&lt;string, .tensorflow.FeatureConfiguration&gt; feature_map = 1;</code>
   */

  public FeatureConfiguration getFeatureMapOrDefault(
      String key,
      FeatureConfiguration defaultValue) {
    if (key == null) { throw new NullPointerException(); }
    java.util.Map<String, FeatureConfiguration> map =
        internalGetFeatureMap().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .tensorflow.FeatureConfiguration&gt; feature_map = 1;</code>
   */

  public FeatureConfiguration getFeatureMapOrThrow(
      String key) {
    if (key == null) { throw new NullPointerException(); }
    java.util.Map<String, FeatureConfiguration> map =
        internalGetFeatureMap().getMap();
    if (!map.containsKey(key)) {
      throw new IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetFeatureMap(),
        FeatureMapDefaultEntryHolder.defaultEntry,
        1);
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<String, FeatureConfiguration> entry
         : internalGetFeatureMap().getMap().entrySet()) {
      com.google.protobuf.MapEntry<String, FeatureConfiguration>
      featureMap__ = FeatureMapDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, featureMap__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ExampleParserConfiguration)) {
      return super.equals(obj);
    }
    ExampleParserConfiguration other = (ExampleParserConfiguration) obj;

    if (!internalGetFeatureMap().equals(
        other.internalGetFeatureMap())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetFeatureMap().getMap().isEmpty()) {
      hash = (37 * hash) + FEATURE_MAP_FIELD_NUMBER;
      hash = (53 * hash) + internalGetFeatureMap().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ExampleParserConfiguration parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ExampleParserConfiguration parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ExampleParserConfiguration parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ExampleParserConfiguration parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ExampleParserConfiguration parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ExampleParserConfiguration parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ExampleParserConfiguration parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ExampleParserConfiguration parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ExampleParserConfiguration parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ExampleParserConfiguration parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ExampleParserConfiguration parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ExampleParserConfiguration parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ExampleParserConfiguration prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tensorflow.ExampleParserConfiguration}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tensorflow.ExampleParserConfiguration)
      ExampleParserConfigurationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ExampleParserConfigurationProtos.internal_static_tensorflow_ExampleParserConfiguration_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetFeatureMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableFeatureMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ExampleParserConfigurationProtos.internal_static_tensorflow_ExampleParserConfiguration_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ExampleParserConfiguration.class, Builder.class);
    }

    // Construct using org.tensorflow.example.ExampleParserConfiguration.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      internalGetMutableFeatureMap().clear();
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ExampleParserConfigurationProtos.internal_static_tensorflow_ExampleParserConfiguration_descriptor;
    }

    @Override
    public ExampleParserConfiguration getDefaultInstanceForType() {
      return ExampleParserConfiguration.getDefaultInstance();
    }

    @Override
    public ExampleParserConfiguration build() {
      ExampleParserConfiguration result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ExampleParserConfiguration buildPartial() {
      ExampleParserConfiguration result = new ExampleParserConfiguration(this);
      int from_bitField0_ = bitField0_;
      result.featureMap_ = internalGetFeatureMap();
      result.featureMap_.makeImmutable();
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ExampleParserConfiguration) {
        return mergeFrom((ExampleParserConfiguration)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ExampleParserConfiguration other) {
      if (other == ExampleParserConfiguration.getDefaultInstance()) return this;
      internalGetMutableFeatureMap().mergeFrom(
          other.internalGetFeatureMap());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ExampleParserConfiguration parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ExampleParserConfiguration) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        String, FeatureConfiguration> featureMap_;
    private com.google.protobuf.MapField<String, FeatureConfiguration>
    internalGetFeatureMap() {
      if (featureMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            FeatureMapDefaultEntryHolder.defaultEntry);
      }
      return featureMap_;
    }
    private com.google.protobuf.MapField<String, FeatureConfiguration>
    internalGetMutableFeatureMap() {
      onChanged();;
      if (featureMap_ == null) {
        featureMap_ = com.google.protobuf.MapField.newMapField(
            FeatureMapDefaultEntryHolder.defaultEntry);
      }
      if (!featureMap_.isMutable()) {
        featureMap_ = featureMap_.copy();
      }
      return featureMap_;
    }

    public int getFeatureMapCount() {
      return internalGetFeatureMap().getMap().size();
    }
    /**
     * <code>map&lt;string, .tensorflow.FeatureConfiguration&gt; feature_map = 1;</code>
     */

    public boolean containsFeatureMap(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetFeatureMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getFeatureMapMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, FeatureConfiguration> getFeatureMap() {
      return getFeatureMapMap();
    }
    /**
     * <code>map&lt;string, .tensorflow.FeatureConfiguration&gt; feature_map = 1;</code>
     */

    public java.util.Map<String, FeatureConfiguration> getFeatureMapMap() {
      return internalGetFeatureMap().getMap();
    }
    /**
     * <code>map&lt;string, .tensorflow.FeatureConfiguration&gt; feature_map = 1;</code>
     */

    public FeatureConfiguration getFeatureMapOrDefault(
        String key,
        FeatureConfiguration defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, FeatureConfiguration> map =
          internalGetFeatureMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .tensorflow.FeatureConfiguration&gt; feature_map = 1;</code>
     */

    public FeatureConfiguration getFeatureMapOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, FeatureConfiguration> map =
          internalGetFeatureMap().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearFeatureMap() {
      internalGetMutableFeatureMap().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .tensorflow.FeatureConfiguration&gt; feature_map = 1;</code>
     */

    public Builder removeFeatureMap(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      internalGetMutableFeatureMap().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @Deprecated
    public java.util.Map<String, FeatureConfiguration>
    getMutableFeatureMap() {
      return internalGetMutableFeatureMap().getMutableMap();
    }
    /**
     * <code>map&lt;string, .tensorflow.FeatureConfiguration&gt; feature_map = 1;</code>
     */
    public Builder putFeatureMap(
        String key,
        FeatureConfiguration value) {
      if (key == null) { throw new NullPointerException(); }
      if (value == null) { throw new NullPointerException(); }
      internalGetMutableFeatureMap().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .tensorflow.FeatureConfiguration&gt; feature_map = 1;</code>
     */

    public Builder putAllFeatureMap(
        java.util.Map<String, FeatureConfiguration> values) {
      internalGetMutableFeatureMap().getMutableMap()
          .putAll(values);
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tensorflow.ExampleParserConfiguration)
  }

  // @@protoc_insertion_point(class_scope:tensorflow.ExampleParserConfiguration)
  private static final ExampleParserConfiguration DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ExampleParserConfiguration();
  }

  public static ExampleParserConfiguration getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExampleParserConfiguration>
      PARSER = new com.google.protobuf.AbstractParser<ExampleParserConfiguration>() {
    @Override
    public ExampleParserConfiguration parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ExampleParserConfiguration(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ExampleParserConfiguration> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ExampleParserConfiguration> getParserForType() {
    return PARSER;
  }

  @Override
  public ExampleParserConfiguration getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

