// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/example/feature.proto

package org.tensorflow.example;

public interface FeatureListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.FeatureList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tensorflow.Feature feature = 1;</code>
   */
  java.util.List<Feature>
      getFeatureList();
  /**
   * <code>repeated .tensorflow.Feature feature = 1;</code>
   */
  Feature getFeature(int index);
  /**
   * <code>repeated .tensorflow.Feature feature = 1;</code>
   */
  int getFeatureCount();
  /**
   * <code>repeated .tensorflow.Feature feature = 1;</code>
   */
  java.util.List<? extends FeatureOrBuilder>
      getFeatureOrBuilderList();
  /**
   * <code>repeated .tensorflow.Feature feature = 1;</code>
   */
  FeatureOrBuilder getFeatureOrBuilder(
          int index);
}
