// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/example/feature.proto

package org.tensorflow.example;

/**
 * Protobuf type {@code tensorflow.FeatureLists}
 */
public  final class FeatureLists extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tensorflow.FeatureLists)
        FeatureListsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FeatureLists.newBuilder() to construct.
  private FeatureLists(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FeatureLists() {
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FeatureLists(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              featureList_ = com.google.protobuf.MapField.newMapField(
                  FeatureListDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<String, FeatureList>
            featureList__ = input.readMessage(
                FeatureListDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            featureList_.getMutableMap().put(
                featureList__.getKey(), featureList__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return FeatureProtos.internal_static_tensorflow_FeatureLists_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetFeatureList();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return FeatureProtos.internal_static_tensorflow_FeatureLists_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            FeatureLists.class, Builder.class);
  }

  public static final int FEATURE_LIST_FIELD_NUMBER = 1;
  private static final class FeatureListDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        String, FeatureList> defaultEntry =
            com.google.protobuf.MapEntry
            .<String, FeatureList>newDefaultInstance(
                FeatureProtos.internal_static_tensorflow_FeatureLists_FeatureListEntry_descriptor,
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                FeatureList.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      String, FeatureList> featureList_;
  private com.google.protobuf.MapField<String, FeatureList>
  internalGetFeatureList() {
    if (featureList_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          FeatureListDefaultEntryHolder.defaultEntry);
    }
    return featureList_;
  }

  public int getFeatureListCount() {
    return internalGetFeatureList().getMap().size();
  }
  /**
   * <pre>
   * Map from feature name to feature list.
   * </pre>
   *
   * <code>map&lt;string, .tensorflow.FeatureList&gt; feature_list = 1;</code>
   */

  public boolean containsFeatureList(
      String key) {
    if (key == null) { throw new NullPointerException(); }
    return internalGetFeatureList().getMap().containsKey(key);
  }
  /**
   * Use {@link #getFeatureListMap()} instead.
   */
  @Deprecated
  public java.util.Map<String, FeatureList> getFeatureList() {
    return getFeatureListMap();
  }
  /**
   * <pre>
   * Map from feature name to feature list.
   * </pre>
   *
   * <code>map&lt;string, .tensorflow.FeatureList&gt; feature_list = 1;</code>
   */

  public java.util.Map<String, FeatureList> getFeatureListMap() {
    return internalGetFeatureList().getMap();
  }
  /**
   * <pre>
   * Map from feature name to feature list.
   * </pre>
   *
   * <code>map&lt;string, .tensorflow.FeatureList&gt; feature_list = 1;</code>
   */

  public FeatureList getFeatureListOrDefault(
      String key,
      FeatureList defaultValue) {
    if (key == null) { throw new NullPointerException(); }
    java.util.Map<String, FeatureList> map =
        internalGetFeatureList().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * Map from feature name to feature list.
   * </pre>
   *
   * <code>map&lt;string, .tensorflow.FeatureList&gt; feature_list = 1;</code>
   */

  public FeatureList getFeatureListOrThrow(
      String key) {
    if (key == null) { throw new NullPointerException(); }
    java.util.Map<String, FeatureList> map =
        internalGetFeatureList().getMap();
    if (!map.containsKey(key)) {
      throw new IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetFeatureList(),
        FeatureListDefaultEntryHolder.defaultEntry,
        1);
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<String, FeatureList> entry
         : internalGetFeatureList().getMap().entrySet()) {
      com.google.protobuf.MapEntry<String, FeatureList>
      featureList__ = FeatureListDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, featureList__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof FeatureLists)) {
      return super.equals(obj);
    }
    FeatureLists other = (FeatureLists) obj;

    if (!internalGetFeatureList().equals(
        other.internalGetFeatureList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetFeatureList().getMap().isEmpty()) {
      hash = (37 * hash) + FEATURE_LIST_FIELD_NUMBER;
      hash = (53 * hash) + internalGetFeatureList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static FeatureLists parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FeatureLists parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FeatureLists parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FeatureLists parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FeatureLists parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FeatureLists parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FeatureLists parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static FeatureLists parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static FeatureLists parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static FeatureLists parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static FeatureLists parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static FeatureLists parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(FeatureLists prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tensorflow.FeatureLists}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tensorflow.FeatureLists)
          FeatureListsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FeatureProtos.internal_static_tensorflow_FeatureLists_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetFeatureList();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableFeatureList();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FeatureProtos.internal_static_tensorflow_FeatureLists_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FeatureLists.class, Builder.class);
    }

    // Construct using org.tensorflow.example.FeatureLists.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      internalGetMutableFeatureList().clear();
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return FeatureProtos.internal_static_tensorflow_FeatureLists_descriptor;
    }

    @Override
    public FeatureLists getDefaultInstanceForType() {
      return FeatureLists.getDefaultInstance();
    }

    @Override
    public FeatureLists build() {
      FeatureLists result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public FeatureLists buildPartial() {
      FeatureLists result = new FeatureLists(this);
      int from_bitField0_ = bitField0_;
      result.featureList_ = internalGetFeatureList();
      result.featureList_.makeImmutable();
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof FeatureLists) {
        return mergeFrom((FeatureLists)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(FeatureLists other) {
      if (other == FeatureLists.getDefaultInstance()) return this;
      internalGetMutableFeatureList().mergeFrom(
          other.internalGetFeatureList());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      FeatureLists parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (FeatureLists) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        String, FeatureList> featureList_;
    private com.google.protobuf.MapField<String, FeatureList>
    internalGetFeatureList() {
      if (featureList_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            FeatureListDefaultEntryHolder.defaultEntry);
      }
      return featureList_;
    }
    private com.google.protobuf.MapField<String, FeatureList>
    internalGetMutableFeatureList() {
      onChanged();;
      if (featureList_ == null) {
        featureList_ = com.google.protobuf.MapField.newMapField(
            FeatureListDefaultEntryHolder.defaultEntry);
      }
      if (!featureList_.isMutable()) {
        featureList_ = featureList_.copy();
      }
      return featureList_;
    }

    public int getFeatureListCount() {
      return internalGetFeatureList().getMap().size();
    }
    /**
     * <pre>
     * Map from feature name to feature list.
     * </pre>
     *
     * <code>map&lt;string, .tensorflow.FeatureList&gt; feature_list = 1;</code>
     */

    public boolean containsFeatureList(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetFeatureList().getMap().containsKey(key);
    }
    /**
     * Use {@link #getFeatureListMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, FeatureList> getFeatureList() {
      return getFeatureListMap();
    }
    /**
     * <pre>
     * Map from feature name to feature list.
     * </pre>
     *
     * <code>map&lt;string, .tensorflow.FeatureList&gt; feature_list = 1;</code>
     */

    public java.util.Map<String, FeatureList> getFeatureListMap() {
      return internalGetFeatureList().getMap();
    }
    /**
     * <pre>
     * Map from feature name to feature list.
     * </pre>
     *
     * <code>map&lt;string, .tensorflow.FeatureList&gt; feature_list = 1;</code>
     */

    public FeatureList getFeatureListOrDefault(
        String key,
        FeatureList defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, FeatureList> map =
          internalGetFeatureList().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Map from feature name to feature list.
     * </pre>
     *
     * <code>map&lt;string, .tensorflow.FeatureList&gt; feature_list = 1;</code>
     */

    public FeatureList getFeatureListOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, FeatureList> map =
          internalGetFeatureList().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearFeatureList() {
      internalGetMutableFeatureList().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * Map from feature name to feature list.
     * </pre>
     *
     * <code>map&lt;string, .tensorflow.FeatureList&gt; feature_list = 1;</code>
     */

    public Builder removeFeatureList(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      internalGetMutableFeatureList().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @Deprecated
    public java.util.Map<String, FeatureList>
    getMutableFeatureList() {
      return internalGetMutableFeatureList().getMutableMap();
    }
    /**
     * <pre>
     * Map from feature name to feature list.
     * </pre>
     *
     * <code>map&lt;string, .tensorflow.FeatureList&gt; feature_list = 1;</code>
     */
    public Builder putFeatureList(
        String key,
        FeatureList value) {
      if (key == null) { throw new NullPointerException(); }
      if (value == null) { throw new NullPointerException(); }
      internalGetMutableFeatureList().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     * Map from feature name to feature list.
     * </pre>
     *
     * <code>map&lt;string, .tensorflow.FeatureList&gt; feature_list = 1;</code>
     */

    public Builder putAllFeatureList(
        java.util.Map<String, FeatureList> values) {
      internalGetMutableFeatureList().getMutableMap()
          .putAll(values);
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tensorflow.FeatureLists)
  }

  // @@protoc_insertion_point(class_scope:tensorflow.FeatureLists)
  private static final FeatureLists DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new FeatureLists();
  }

  public static FeatureLists getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FeatureLists>
      PARSER = new com.google.protobuf.AbstractParser<FeatureLists>() {
    @Override
    public FeatureLists parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FeatureLists(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FeatureLists> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<FeatureLists> getParserForType() {
    return PARSER;
  }

  @Override
  public FeatureLists getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

