// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/example/feature.proto

package org.tensorflow.example;

public interface FeatureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.Feature)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tensorflow.BytesList bytes_list = 1;</code>
   */
  boolean hasBytesList();
  /**
   * <code>.tensorflow.BytesList bytes_list = 1;</code>
   */
  BytesList getBytesList();
  /**
   * <code>.tensorflow.BytesList bytes_list = 1;</code>
   */
  BytesListOrBuilder getBytesListOrBuilder();

  /**
   * <code>.tensorflow.FloatList float_list = 2;</code>
   */
  boolean hasFloatList();
  /**
   * <code>.tensorflow.FloatList float_list = 2;</code>
   */
  FloatList getFloatList();
  /**
   * <code>.tensorflow.FloatList float_list = 2;</code>
   */
  FloatListOrBuilder getFloatListOrBuilder();

  /**
   * <code>.tensorflow.Int64List int64_list = 3;</code>
   */
  boolean hasInt64List();
  /**
   * <code>.tensorflow.Int64List int64_list = 3;</code>
   */
  Int64List getInt64List();
  /**
   * <code>.tensorflow.Int64List int64_list = 3;</code>
   */
  Int64ListOrBuilder getInt64ListOrBuilder();

  public Feature.KindCase getKindCase();
}
