// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apis/common/example.proto

package tensorflow.common;
import tensorflow.common.*;
import tensorflow.serving.*;

public final class ExampleProtos {
  private ExampleProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ExampleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:angel.serving.Example)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.angel.serving.Features features = 1;</code>
     */
    boolean hasFeatures();
    /**
     * <code>.angel.serving.Features features = 1;</code>
     */
    FeatureProtos.Features getFeatures();
    /**
     * <code>.angel.serving.Features features = 1;</code>
     */
    FeatureProtos.FeaturesOrBuilder getFeaturesOrBuilder();
  }
  /**
   * Protobuf type {@code angel.serving.Example}
   */
  public  static final class Example extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:angel.serving.Example)
      ExampleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Example.newBuilder() to construct.
    private Example(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Example() {
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Example(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              FeatureProtos.Features.Builder subBuilder = null;
              if (features_ != null) {
                subBuilder = features_.toBuilder();
              }
              features_ = input.readMessage(FeatureProtos.Features.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(features_);
                features_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ExampleProtos.internal_static_angel_serving_Example_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ExampleProtos.internal_static_angel_serving_Example_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Example.class, Builder.class);
    }

    public static final int FEATURES_FIELD_NUMBER = 1;
    private FeatureProtos.Features features_;
    /**
     * <code>.angel.serving.Features features = 1;</code>
     */
    public boolean hasFeatures() {
      return features_ != null;
    }
    /**
     * <code>.angel.serving.Features features = 1;</code>
     */
    public FeatureProtos.Features getFeatures() {
      return features_ == null ? FeatureProtos.Features.getDefaultInstance() : features_;
    }
    /**
     * <code>.angel.serving.Features features = 1;</code>
     */
    public FeatureProtos.FeaturesOrBuilder getFeaturesOrBuilder() {
      return getFeatures();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (features_ != null) {
        output.writeMessage(1, getFeatures());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (features_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getFeatures());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Example)) {
        return super.equals(obj);
      }
      Example other = (Example) obj;

      boolean result = true;
      result = result && (hasFeatures() == other.hasFeatures());
      if (hasFeatures()) {
        result = result && getFeatures()
            .equals(other.getFeatures());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFeatures()) {
        hash = (37 * hash) + FEATURES_FIELD_NUMBER;
        hash = (53 * hash) + getFeatures().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Example parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Example parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Example parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Example parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Example parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Example parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Example parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Example parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Example parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Example parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Example parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Example parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Example prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code angel.serving.Example}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:angel.serving.Example)
        ExampleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ExampleProtos.internal_static_angel_serving_Example_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ExampleProtos.internal_static_angel_serving_Example_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Example.class, Builder.class);
      }

      // Construct using ExampleProtos.Example.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (featuresBuilder_ == null) {
          features_ = null;
        } else {
          features_ = null;
          featuresBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ExampleProtos.internal_static_angel_serving_Example_descriptor;
      }

      public Example getDefaultInstanceForType() {
        return Example.getDefaultInstance();
      }

      public Example build() {
        Example result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Example buildPartial() {
        Example result = new Example(this);
        if (featuresBuilder_ == null) {
          result.features_ = features_;
        } else {
          result.features_ = featuresBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Example) {
          return mergeFrom((Example)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Example other) {
        if (other == Example.getDefaultInstance()) return this;
        if (other.hasFeatures()) {
          mergeFeatures(other.getFeatures());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Example parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Example) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private FeatureProtos.Features features_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          FeatureProtos.Features, FeatureProtos.Features.Builder, FeatureProtos.FeaturesOrBuilder> featuresBuilder_;
      /**
       * <code>.angel.serving.Features features = 1;</code>
       */
      public boolean hasFeatures() {
        return featuresBuilder_ != null || features_ != null;
      }
      /**
       * <code>.angel.serving.Features features = 1;</code>
       */
      public FeatureProtos.Features getFeatures() {
        if (featuresBuilder_ == null) {
          return features_ == null ? FeatureProtos.Features.getDefaultInstance() : features_;
        } else {
          return featuresBuilder_.getMessage();
        }
      }
      /**
       * <code>.angel.serving.Features features = 1;</code>
       */
      public Builder setFeatures(FeatureProtos.Features value) {
        if (featuresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          features_ = value;
          onChanged();
        } else {
          featuresBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.angel.serving.Features features = 1;</code>
       */
      public Builder setFeatures(
          FeatureProtos.Features.Builder builderForValue) {
        if (featuresBuilder_ == null) {
          features_ = builderForValue.build();
          onChanged();
        } else {
          featuresBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.angel.serving.Features features = 1;</code>
       */
      public Builder mergeFeatures(FeatureProtos.Features value) {
        if (featuresBuilder_ == null) {
          if (features_ != null) {
            features_ =
              FeatureProtos.Features.newBuilder(features_).mergeFrom(value).buildPartial();
          } else {
            features_ = value;
          }
          onChanged();
        } else {
          featuresBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.angel.serving.Features features = 1;</code>
       */
      public Builder clearFeatures() {
        if (featuresBuilder_ == null) {
          features_ = null;
          onChanged();
        } else {
          features_ = null;
          featuresBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.angel.serving.Features features = 1;</code>
       */
      public FeatureProtos.Features.Builder getFeaturesBuilder() {
        
        onChanged();
        return getFeaturesFieldBuilder().getBuilder();
      }
      /**
       * <code>.angel.serving.Features features = 1;</code>
       */
      public FeatureProtos.FeaturesOrBuilder getFeaturesOrBuilder() {
        if (featuresBuilder_ != null) {
          return featuresBuilder_.getMessageOrBuilder();
        } else {
          return features_ == null ?
              FeatureProtos.Features.getDefaultInstance() : features_;
        }
      }
      /**
       * <code>.angel.serving.Features features = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          FeatureProtos.Features, FeatureProtos.Features.Builder, FeatureProtos.FeaturesOrBuilder> 
          getFeaturesFieldBuilder() {
        if (featuresBuilder_ == null) {
          featuresBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              FeatureProtos.Features, FeatureProtos.Features.Builder, FeatureProtos.FeaturesOrBuilder>(
                  getFeatures(),
                  getParentForChildren(),
                  isClean());
          features_ = null;
        }
        return featuresBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:angel.serving.Example)
    }

    // @@protoc_insertion_point(class_scope:angel.serving.Example)
    private static final Example DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Example();
    }

    public static Example getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Example>
        PARSER = new com.google.protobuf.AbstractParser<Example>() {
      public Example parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Example(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Example> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Example> getParserForType() {
      return PARSER;
    }

    public Example getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SequenceExampleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:angel.serving.SequenceExample)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.angel.serving.Features context = 1;</code>
     */
    boolean hasContext();
    /**
     * <code>.angel.serving.Features context = 1;</code>
     */
    FeatureProtos.Features getContext();
    /**
     * <code>.angel.serving.Features context = 1;</code>
     */
    FeatureProtos.FeaturesOrBuilder getContextOrBuilder();

    /**
     * <code>.angel.serving.FeatureLists feature_lists = 2;</code>
     */
    boolean hasFeatureLists();
    /**
     * <code>.angel.serving.FeatureLists feature_lists = 2;</code>
     */
    FeatureProtos.FeatureLists getFeatureLists();
    /**
     * <code>.angel.serving.FeatureLists feature_lists = 2;</code>
     */
    FeatureProtos.FeatureListsOrBuilder getFeatureListsOrBuilder();
  }
  /**
   * Protobuf type {@code angel.serving.SequenceExample}
   */
  public  static final class SequenceExample extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:angel.serving.SequenceExample)
      SequenceExampleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SequenceExample.newBuilder() to construct.
    private SequenceExample(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SequenceExample() {
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SequenceExample(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              FeatureProtos.Features.Builder subBuilder = null;
              if (context_ != null) {
                subBuilder = context_.toBuilder();
              }
              context_ = input.readMessage(FeatureProtos.Features.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(context_);
                context_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              FeatureProtos.FeatureLists.Builder subBuilder = null;
              if (featureLists_ != null) {
                subBuilder = featureLists_.toBuilder();
              }
              featureLists_ = input.readMessage(FeatureProtos.FeatureLists.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(featureLists_);
                featureLists_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ExampleProtos.internal_static_angel_serving_SequenceExample_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ExampleProtos.internal_static_angel_serving_SequenceExample_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SequenceExample.class, Builder.class);
    }

    public static final int CONTEXT_FIELD_NUMBER = 1;
    private FeatureProtos.Features context_;
    /**
     * <code>.angel.serving.Features context = 1;</code>
     */
    public boolean hasContext() {
      return context_ != null;
    }
    /**
     * <code>.angel.serving.Features context = 1;</code>
     */
    public FeatureProtos.Features getContext() {
      return context_ == null ? FeatureProtos.Features.getDefaultInstance() : context_;
    }
    /**
     * <code>.angel.serving.Features context = 1;</code>
     */
    public FeatureProtos.FeaturesOrBuilder getContextOrBuilder() {
      return getContext();
    }

    public static final int FEATURE_LISTS_FIELD_NUMBER = 2;
    private FeatureProtos.FeatureLists featureLists_;
    /**
     * <code>.angel.serving.FeatureLists feature_lists = 2;</code>
     */
    public boolean hasFeatureLists() {
      return featureLists_ != null;
    }
    /**
     * <code>.angel.serving.FeatureLists feature_lists = 2;</code>
     */
    public FeatureProtos.FeatureLists getFeatureLists() {
      return featureLists_ == null ? FeatureProtos.FeatureLists.getDefaultInstance() : featureLists_;
    }
    /**
     * <code>.angel.serving.FeatureLists feature_lists = 2;</code>
     */
    public FeatureProtos.FeatureListsOrBuilder getFeatureListsOrBuilder() {
      return getFeatureLists();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (context_ != null) {
        output.writeMessage(1, getContext());
      }
      if (featureLists_ != null) {
        output.writeMessage(2, getFeatureLists());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (context_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getContext());
      }
      if (featureLists_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getFeatureLists());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SequenceExample)) {
        return super.equals(obj);
      }
      SequenceExample other = (SequenceExample) obj;

      boolean result = true;
      result = result && (hasContext() == other.hasContext());
      if (hasContext()) {
        result = result && getContext()
            .equals(other.getContext());
      }
      result = result && (hasFeatureLists() == other.hasFeatureLists());
      if (hasFeatureLists()) {
        result = result && getFeatureLists()
            .equals(other.getFeatureLists());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasContext()) {
        hash = (37 * hash) + CONTEXT_FIELD_NUMBER;
        hash = (53 * hash) + getContext().hashCode();
      }
      if (hasFeatureLists()) {
        hash = (37 * hash) + FEATURE_LISTS_FIELD_NUMBER;
        hash = (53 * hash) + getFeatureLists().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SequenceExample parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SequenceExample parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SequenceExample parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SequenceExample parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SequenceExample parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SequenceExample parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SequenceExample parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SequenceExample parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SequenceExample parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SequenceExample parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SequenceExample parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SequenceExample parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SequenceExample prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code angel.serving.SequenceExample}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:angel.serving.SequenceExample)
        SequenceExampleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ExampleProtos.internal_static_angel_serving_SequenceExample_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ExampleProtos.internal_static_angel_serving_SequenceExample_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SequenceExample.class, Builder.class);
      }

      // Construct using ExampleProtos.SequenceExample.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (contextBuilder_ == null) {
          context_ = null;
        } else {
          context_ = null;
          contextBuilder_ = null;
        }
        if (featureListsBuilder_ == null) {
          featureLists_ = null;
        } else {
          featureLists_ = null;
          featureListsBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ExampleProtos.internal_static_angel_serving_SequenceExample_descriptor;
      }

      public SequenceExample getDefaultInstanceForType() {
        return SequenceExample.getDefaultInstance();
      }

      public SequenceExample build() {
        SequenceExample result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SequenceExample buildPartial() {
        SequenceExample result = new SequenceExample(this);
        if (contextBuilder_ == null) {
          result.context_ = context_;
        } else {
          result.context_ = contextBuilder_.build();
        }
        if (featureListsBuilder_ == null) {
          result.featureLists_ = featureLists_;
        } else {
          result.featureLists_ = featureListsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SequenceExample) {
          return mergeFrom((SequenceExample)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SequenceExample other) {
        if (other == SequenceExample.getDefaultInstance()) return this;
        if (other.hasContext()) {
          mergeContext(other.getContext());
        }
        if (other.hasFeatureLists()) {
          mergeFeatureLists(other.getFeatureLists());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SequenceExample parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SequenceExample) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private FeatureProtos.Features context_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          FeatureProtos.Features, FeatureProtos.Features.Builder, FeatureProtos.FeaturesOrBuilder> contextBuilder_;
      /**
       * <code>.angel.serving.Features context = 1;</code>
       */
      public boolean hasContext() {
        return contextBuilder_ != null || context_ != null;
      }
      /**
       * <code>.angel.serving.Features context = 1;</code>
       */
      public FeatureProtos.Features getContext() {
        if (contextBuilder_ == null) {
          return context_ == null ? FeatureProtos.Features.getDefaultInstance() : context_;
        } else {
          return contextBuilder_.getMessage();
        }
      }
      /**
       * <code>.angel.serving.Features context = 1;</code>
       */
      public Builder setContext(FeatureProtos.Features value) {
        if (contextBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          context_ = value;
          onChanged();
        } else {
          contextBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.angel.serving.Features context = 1;</code>
       */
      public Builder setContext(
          FeatureProtos.Features.Builder builderForValue) {
        if (contextBuilder_ == null) {
          context_ = builderForValue.build();
          onChanged();
        } else {
          contextBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.angel.serving.Features context = 1;</code>
       */
      public Builder mergeContext(FeatureProtos.Features value) {
        if (contextBuilder_ == null) {
          if (context_ != null) {
            context_ =
              FeatureProtos.Features.newBuilder(context_).mergeFrom(value).buildPartial();
          } else {
            context_ = value;
          }
          onChanged();
        } else {
          contextBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.angel.serving.Features context = 1;</code>
       */
      public Builder clearContext() {
        if (contextBuilder_ == null) {
          context_ = null;
          onChanged();
        } else {
          context_ = null;
          contextBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.angel.serving.Features context = 1;</code>
       */
      public FeatureProtos.Features.Builder getContextBuilder() {
        
        onChanged();
        return getContextFieldBuilder().getBuilder();
      }
      /**
       * <code>.angel.serving.Features context = 1;</code>
       */
      public FeatureProtos.FeaturesOrBuilder getContextOrBuilder() {
        if (contextBuilder_ != null) {
          return contextBuilder_.getMessageOrBuilder();
        } else {
          return context_ == null ?
              FeatureProtos.Features.getDefaultInstance() : context_;
        }
      }
      /**
       * <code>.angel.serving.Features context = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          FeatureProtos.Features, FeatureProtos.Features.Builder, FeatureProtos.FeaturesOrBuilder> 
          getContextFieldBuilder() {
        if (contextBuilder_ == null) {
          contextBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              FeatureProtos.Features, FeatureProtos.Features.Builder, FeatureProtos.FeaturesOrBuilder>(
                  getContext(),
                  getParentForChildren(),
                  isClean());
          context_ = null;
        }
        return contextBuilder_;
      }

      private FeatureProtos.FeatureLists featureLists_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          FeatureProtos.FeatureLists, FeatureProtos.FeatureLists.Builder, FeatureProtos.FeatureListsOrBuilder> featureListsBuilder_;
      /**
       * <code>.angel.serving.FeatureLists feature_lists = 2;</code>
       */
      public boolean hasFeatureLists() {
        return featureListsBuilder_ != null || featureLists_ != null;
      }
      /**
       * <code>.angel.serving.FeatureLists feature_lists = 2;</code>
       */
      public FeatureProtos.FeatureLists getFeatureLists() {
        if (featureListsBuilder_ == null) {
          return featureLists_ == null ? FeatureProtos.FeatureLists.getDefaultInstance() : featureLists_;
        } else {
          return featureListsBuilder_.getMessage();
        }
      }
      /**
       * <code>.angel.serving.FeatureLists feature_lists = 2;</code>
       */
      public Builder setFeatureLists(FeatureProtos.FeatureLists value) {
        if (featureListsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          featureLists_ = value;
          onChanged();
        } else {
          featureListsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.angel.serving.FeatureLists feature_lists = 2;</code>
       */
      public Builder setFeatureLists(
          FeatureProtos.FeatureLists.Builder builderForValue) {
        if (featureListsBuilder_ == null) {
          featureLists_ = builderForValue.build();
          onChanged();
        } else {
          featureListsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.angel.serving.FeatureLists feature_lists = 2;</code>
       */
      public Builder mergeFeatureLists(FeatureProtos.FeatureLists value) {
        if (featureListsBuilder_ == null) {
          if (featureLists_ != null) {
            featureLists_ =
              FeatureProtos.FeatureLists.newBuilder(featureLists_).mergeFrom(value).buildPartial();
          } else {
            featureLists_ = value;
          }
          onChanged();
        } else {
          featureListsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.angel.serving.FeatureLists feature_lists = 2;</code>
       */
      public Builder clearFeatureLists() {
        if (featureListsBuilder_ == null) {
          featureLists_ = null;
          onChanged();
        } else {
          featureLists_ = null;
          featureListsBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.angel.serving.FeatureLists feature_lists = 2;</code>
       */
      public FeatureProtos.FeatureLists.Builder getFeatureListsBuilder() {
        
        onChanged();
        return getFeatureListsFieldBuilder().getBuilder();
      }
      /**
       * <code>.angel.serving.FeatureLists feature_lists = 2;</code>
       */
      public FeatureProtos.FeatureListsOrBuilder getFeatureListsOrBuilder() {
        if (featureListsBuilder_ != null) {
          return featureListsBuilder_.getMessageOrBuilder();
        } else {
          return featureLists_ == null ?
              FeatureProtos.FeatureLists.getDefaultInstance() : featureLists_;
        }
      }
      /**
       * <code>.angel.serving.FeatureLists feature_lists = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          FeatureProtos.FeatureLists, FeatureProtos.FeatureLists.Builder, FeatureProtos.FeatureListsOrBuilder> 
          getFeatureListsFieldBuilder() {
        if (featureListsBuilder_ == null) {
          featureListsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              FeatureProtos.FeatureLists, FeatureProtos.FeatureLists.Builder, FeatureProtos.FeatureListsOrBuilder>(
                  getFeatureLists(),
                  getParentForChildren(),
                  isClean());
          featureLists_ = null;
        }
        return featureListsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:angel.serving.SequenceExample)
    }

    // @@protoc_insertion_point(class_scope:angel.serving.SequenceExample)
    private static final SequenceExample DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SequenceExample();
    }

    public static SequenceExample getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SequenceExample>
        PARSER = new com.google.protobuf.AbstractParser<SequenceExample>() {
      public SequenceExample parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SequenceExample(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SequenceExample> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SequenceExample> getParserForType() {
      return PARSER;
    }

    public SequenceExample getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_angel_serving_Example_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_angel_serving_Example_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_angel_serving_SequenceExample_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_angel_serving_SequenceExample_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\031apis/common/example.proto\022\rangel.servi" +
      "ng\032\031apis/common/feature.proto\"4\n\007Example" +
      "\022)\n\010features\030\001 \001(\0132\027.angel.serving.Featu" +
      "res\"o\n\017SequenceExample\022(\n\007context\030\001 \001(\0132" +
      "\027.angel.serving.Features\0222\n\rfeature_list" +
      "s\030\002 \001(\0132\033.angel.serving.FeatureListsB8\n%" +
      "com.tencent.angel.serving.apis.commonB\rE" +
      "xampleProtosP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          FeatureProtos.getDescriptor(),
        }, assigner);
    internal_static_angel_serving_Example_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_angel_serving_Example_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_angel_serving_Example_descriptor,
        new String[] { "Features", });
    internal_static_angel_serving_SequenceExample_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_angel_serving_SequenceExample_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_angel_serving_SequenceExample_descriptor,
        new String[] { "Context", "FeatureLists", });
    FeatureProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
